### ISSUE TITLE
provide units

### ISSUE THREAD

**Issue by zingale** [wmwolf/py_mesa_reader#10]
It would be nice if we could query a `MesaData` object for the units of a quantity, e.g., like

```
p = mr.MesaData("profile99.data")
p.units_of("radius")
```

**Comment by wmwolf** [comment]
I agree that this would be nice, but this would require understanding the documentation of `star` and `binary`, and that also assumes that the information is present in that documentation. Often it is implicit that something is in solar units or cgs. One could argue this is a shortcoming in MESA documentation, but as this module is intended to work absent a mesa installation (i.e., someone could send you a mesa history file without your having mesa installed), I don't see a feasible way to add this feature.

Closing, but happy to hear any suggestions to overcome this hurdle.
