### ISSUE TITLE
Publish on PyPi

### ISSUE THREAD

**Issue by Findus23** [wmwolf/py_mesa_reader#13]
Hi,

At the moment when one wants to install py_mesa_reader, one needs to do it via the ZIP from GitHub:
```
pip install https://github.com/wmwolf/py_mesa_reader/archive/master.zip
```

It would be great if you could publish the package on pypi so that people could directly install it via 
```
pip install mesa_reader
```

There is https://pypi.org/project/mesa_reader/ but it seems to contain no files.

**Comment by wmwolf** [comment]
I looked into this a long time ago and struggled to get things working. Hopefully I can get to this some time this summer, now that I'm a bit more plugged into python-land.

**Comment by Findus23** [comment]
In theory it should already be enough to run
```
python3 setup.py sdist
python3 setup.py bdist_wheel
```
to get the `dist/mesa_reader-0.3.0.tar.gz` and  `dist/mesa_reader-0.3.0-py3-none-any.whl` and then running `twine upload dist/mesa_reader-0.3.0*` to upload the file to pypi (after logging in in twine)

**Comment by wmwolf** [comment]
At long last, this is now done.
