### ISSUE TITLE
MesaData cannot handle one-entry history.data

### ISSUE THREAD

**Issue by kailicao** [wmwolf/py_mesa_reader#18]
When history.data contains only one entry, MesaData cannot handle it, as the data(key) method returns an element instead of an array.

For instance, when I use the following code to read a one-entry history.data:
import mesa_reader as mr
h = mr.MesaData('history.data')

I get the following error:
Traceback (most recent call last):

  File E:\MyResearch\MESA\1M_pre_ms_to_wd\LOGS_start\test.py:2 in <module>
    h = mr.MesaData('history.data')

  File D:\Users\KailiCao\anaconda3\lib\site-packages\mesa_reader\__init__.py:129 in __init__
    self.read_data()

  File D:\Users\KailiCao\anaconda3\lib\site-packages\mesa_reader\__init__.py:177 in read_data
    self.read_log_data()

  File D:\Users\KailiCao\anaconda3\lib\site-packages\mesa_reader\__init__.py:208 in read_log_data
    self.remove_backups()

  File D:\Users\KailiCao\anaconda3\lib\site-packages\mesa_reader\__init__.py:673 in remove_backups
    for i in range(len(self.data('model_number')) - 1):

TypeError: len() of unsized object

**Comment by ShaiAvr** [comment]
I am starting to learn MESA and I also encountered this bug. It’s weird that this issue exists for two years without a response. I can look into the code to try and fix this and make a pull request if the author doesn't have time to look at it.

**Comment by ShaiAvr** [comment]
I created a pull request #21 to fix this bug. Adding `ndmin=1` to the `np.genfromtxt` call ensures we get a 1D array and not a scalar even with a single entry, so `MesaData` doesn't crash. Hopefully, this can be merged and published to pypi quickly.

**Comment by wmwolf** [comment]
Thanks, @ShaiAvr, #21 seems to solve the issue. I've merged it in and will include it in the next release once we resolve #20.
